modLoader = "javafml"
loaderVersion = "[4,)"
license = "All Rights Reserved"

[[mods]]
modId = "floatater"
version = "${version}"
displayName = "Floatater"
authors = "BogdanValentin977"
description = '''Brings back the Floatater from the 24w14potato April Fools snapshot: a redstone engine that flies whole contraptions.'''
iconFile = "icon.png"

[[mixins]]
config = "floatater.mixins.json"

[[dependencies.floatater]]
modId = "neoforge"
type = "required"
versionRange = "[26.2.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.floatater]]
modId = "minecraft"
type = "required"
versionRange = "[26.2,26.3)"
ordering = "NONE"
side = "BOTH"
